# Generated by Django 3.2.16 on 2024-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_forbiddenword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='forbiddenword',
            name='word',
            field=models.CharField(max_length=25, unique=True, verbose_name='Запрещенное слово'),
        ),
    ]
